from click.testing import CliRunner as CliRunner
from r2b2.cli import cli as cli
from r2b2.contest import Contest as Contest, ContestType as ContestType
from r2b2.so_bravo import SO_BRAVO as SO_BRAVO
from typing import Any

default_contest: Any
tol: float

def test_simple_so_bravo() -> None: ...
def test_so_bravo_kmins() -> None: ...
def test_min_sample_size() -> None: ...
def test_execute_round_so_bravo() -> None: ...
def test_find_sprob_first_round() -> None: ...
def test_next_sample_size_first_round() -> None: ...
