from r2b2.contest import Contest as Contest, ContestType as ContestType
from r2b2.minerva2 import Minerva2 as Minerva2
from typing import Any

default_contest: Any
tol: float

def test_minerva2_kmins() -> None: ...
def test_simple_minerva2() -> None: ...
def test_min_sample_size() -> None: ...
def test_kmin_upper_bound() -> None: ...
def test_minerva2_first_round_estimate() -> None: ...
def test_minerva2_second_round_estimate() -> None: ...
def test_exceptions() -> None: ...
def test_execute_round_minerva() -> None: ...
def test_minerva2_third_round_estimate() -> None: ...
