from r2b2.cli import cli as cli

def test_interactive_simple() -> None: ...
def test_interactive_given_audit() -> None: ...
def test_interactive_given_contest() -> None: ...
def test_interactive_given_both() -> None: ...
def test_interactive_multi_round() -> None: ...
def test_bulk_min_to_max() -> None: ...
def test_bulk_round_list() -> None: ...
def test_template_contest() -> None: ...
def test_tempalte_election() -> None: ...
def test_template_contest_output_file() -> None: ...
def test_tempalte_election_output_file() -> None: ...
