# Build step #1: build the React front end
FROM ubuntu:focal 

WORKDIR /app

ENV PYTHONUNBUFFERED=1 \
    # prevents python creating .pyc files
    PYTHONDONTWRITEBYTECODE=1 \
    \
    # pip
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    \
    # poetry
    # https://python-poetry.org/docs/configuration/#using-environment-variables
    POETRY_VERSION=1.1.15 \
    # make poetry install to this location
    POETRY_HOME="/opt/poetry" \
    # do not ask any interactive question
    POETRY_NO_INTERACTION=1 
    
ENV PATH /app/node_modules/.bin:$PATH
# prepend poetry and venv to path
ENV PATH="$POETRY_HOME/bin:$VENV_PATH/bin:$PATH"


COPY . .

RUN apt update && apt install -y build-essential curl git

RUN apt-get install -y locales && \
    sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales

ARG DEBIAN_FRONTEND=noninteractive
    
ENV POETRY_VERSION=1.1.15
ENV LC_ALL en_US.UTF-8
ENV ENV LANG en_US.UTF-8
ENV TZ=Etc/UTC

RUN apt-get install -y tzdata

RUN apt install -y python3.8 python3.8-venv libpython3.8-dev libpq-dev graphicsmagick
# Install node: https://github.com/nodesource/distributions/blob/master/README.md#deb		
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | grep -v 'sleep' | bash -
RUN apt-get install -y nodejs

# Install poetry: https://python-poetry.org/docs/master/#osx--linux--bashonwindows-install-instructions
# Keep the local dev POETRY_VERSION in sync with the Heroku config var
RUN curl -sSL https://install.python-poetry.org | python3.8 -
RUN npm install -g yarn

COPY ./server/pyproject.toml .
COPY ./server/poetry.lock .
COPY ./server/alembic.ini .

RUN poetry install

RUN yarn build

EXPOSE 3000
WORKDIR /app
CMD ["poetry", "run", "gunicorn", "-b", ":3000", "server.app:app"]
