import { BallotStatus, Interpretation } from '../../types'
import { contestMocks } from '../MultiJurisdictionAudit/AASetup/Contests/_mocks'
import { IBallot } from '../MultiJurisdictionAudit/RoundManagement/useBallots'
import { IAuditBoard } from '../UserContext'

export const contest = contestMocks.filledTargeted.contests[0]

export const dummyBoards = (): IAuditBoard[] => [
  {
    type: 'audit_board',
    id: 'audit-board-1',
    name: 'Audit Board #1',
    jurisdictionId: 'jurisdiction-1',
    jurisdictionName: 'Jurisdiction 1',
    electionId: '1',
    roundId: 'round-1',
    members: [
      {
        name: 'John Doe',
        affiliation: '',
      },
      {
        name: 'Jane Doe',
        affiliation: 'LIB',
      },
    ],
    signedOffAt: null,
  },
  {
    type: 'audit_board',
    id: 'audit-board-1',
    name: 'Audit Board #1',
    jurisdictionId: 'jurisdiction-1',
    jurisdictionName: 'Jurisdiction 1',
    electionId: '1',
    roundId: 'round-1',
    members: [],
    signedOffAt: null,
  },
]

export const dummyColumnBallots: {
  [keys in
    | 'ballotsNoTabulatorNoContainer'
    | 'ballotsNoContainer'
    | 'ballotsNoTabulator'
    | 'ballotsBoth']: { ballots: IBallot[] }
} = {
  ballotsNoTabulatorNoContainer: {
    ballots: [
      {
        id: 'ballot-id-1',
        batch: {
          name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
          id: 'batch-id-1',
          tabulator: null,
          container: null,
        },
        position: 313,
        status: BallotStatus.AUDITED,
        interpretations: [],
        auditBoard: dummyBoards()[0],
      },
    ],
  },
  ballotsNoContainer: {
    ballots: [
      {
        id: 'ballot-id-1',
        batch: {
          name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
          id: 'batch-id-1',
          tabulator: '11',
          container: null,
        },
        position: 313,
        status: BallotStatus.AUDITED,
        interpretations: [],
        auditBoard: dummyBoards()[0],
      },
    ],
  },
  ballotsNoTabulator: {
    ballots: [
      {
        id: 'ballot-id-1',
        batch: {
          name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
          id: 'batch-id-1',
          tabulator: null,
          container: 'box',
        },
        position: 313,
        status: BallotStatus.AUDITED,
        interpretations: [],
        auditBoard: dummyBoards()[0],
      },
    ],
  },
  ballotsBoth: {
    ballots: [
      {
        id: 'ballot-id-1',
        batch: {
          name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
          id: 'batch-id-1',
          tabulator: '11',
          container: 'box',
        },
        position: 313,
        status: BallotStatus.AUDITED,
        interpretations: [],
        auditBoard: dummyBoards()[0],
      },
    ],
  },
}

export const doneDummyBallots: { ballots: IBallot[] } = {
  ballots: [
    {
      id: 'ballot-id-1',
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id-1',
        tabulator: '11',
        container: null,
      },
      position: 313,
      status: BallotStatus.AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[0],
    },
    {
      id: 'ballot-id-2',
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id-1',
        tabulator: '11',
        container: null,
      },
      position: 2112,
      status: BallotStatus.AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[0],
    },
    {
      id: 'ballot-id-3',
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id-1',
        tabulator: '11',
        container: null,
      },
      position: 1789,
      status: BallotStatus.AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[0],
    },
    {
      id: 'ballot-id-4',
      batch: {
        name: '0003-04-Precinct 31 (Jonesboro Fire Department)',
        id: 'batch-id-1',
        tabulator: '11',
        container: null,
      },
      position: 1965,
      status: BallotStatus.NOT_FOUND,
      interpretations: [],
      auditBoard: dummyBoards()[0],
    },
  ],
}

export const dummyBallots: { ballots: IBallot[] } = {
  ballots: [
    {
      id: 'ballot-id-1',
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id-1',
        tabulator: '11',
        container: null,
      },
      position: 313,
      status: BallotStatus.AUDITED,
      interpretations: [
        {
          contestId: contest.id,
          interpretation: Interpretation.VOTE,
          choiceIds: [contest.choices[0].id],
          comment: 'Good ballot',
        },
      ],
      auditBoard: dummyBoards()[0],
    },
    {
      id: 'ballot-id-2',
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id-1',
        tabulator: '11',
        container: null,
      },
      position: 2112,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[0],
    },
    {
      id: 'ballot-id-3',
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id-1',
        tabulator: '11',
        container: null,
      },
      position: 1789,
      status: BallotStatus.AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[0],
    },
    {
      id: 'ballot-id-4',
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id-2',
        tabulator: '11',
        container: null,
      },
      position: 313,
      status: BallotStatus.AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[0],
    },
    {
      id: 'ballot-id-5',
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id-2',
        tabulator: '11',
        container: null,
      },
      position: 2112,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[0],
    },
    {
      id: 'ballot-id-6',
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id-2',
        tabulator: '11',
        container: null,
      },
      position: 1789,
      status: BallotStatus.AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[0],
    },
    {
      id: 'ballot-id-7',
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id-3',
        tabulator: '11',
        container: null,
      },
      position: 313,
      status: BallotStatus.AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[0],
    },
    {
      id: 'ballot-id-8',
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id-3',
        tabulator: '11',
        container: null,
      },
      position: 2112,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[0],
    },
    {
      id: 'ballot-id-9',
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id-3',
        tabulator: '11',
        container: null,
      },
      position: 1789,
      status: BallotStatus.AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[0],
    },
    {
      id: 'ballot-id-10',
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id-4',
        tabulator: '11',
        container: null,
      },
      position: 313,
      status: BallotStatus.AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[0],
    },
    {
      id: 'ballot-id-11',
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id-4',
        tabulator: '11',
        container: null,
      },
      position: 2112,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-12',
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id-4',
        tabulator: '11',
        container: null,
      },
      position: 1789,
      status: BallotStatus.AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-13',
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id-5',
        tabulator: '11',
        container: null,
      },
      position: 313,
      status: BallotStatus.AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-14',
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id-5',
        tabulator: '11',
        container: null,
      },
      position: 2112,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-15',
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id-5',
        tabulator: '11',
        container: null,
      },
      position: 1789,
      status: BallotStatus.AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-16',
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id-6',
        tabulator: '11',
        container: null,
      },
      position: 313,
      status: BallotStatus.AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-17',
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id-6',
        tabulator: '11',
        container: null,
      },
      position: 2112,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-18',
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id-6',
        tabulator: '11',
        container: null,
      },
      position: 1789,
      status: BallotStatus.AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-19',
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id-7',
        tabulator: '11',
        container: null,
      },
      position: 313,
      status: BallotStatus.AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-20',
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id-7',
        tabulator: '11',
        container: null,
      },
      position: 2112,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-21',
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id-7',
        tabulator: '11',
        container: null,
      },
      position: 1789,
      status: BallotStatus.AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-22',
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id-8',
        tabulator: '11',
        container: null,
      },
      position: 313,
      status: BallotStatus.AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-23',
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id-8',
        tabulator: '11',
        container: null,
      },
      position: 2112,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-24',
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id-8',
        tabulator: '11',
        container: null,
      },
      position: 1789,
      status: BallotStatus.AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-25',
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id-9',
        tabulator: '11',
        container: null,
      },
      position: 313,
      status: BallotStatus.AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-26',
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id-9',
        tabulator: '11',
        container: null,
      },
      position: 2112,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-27',
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id-9',
        tabulator: '11',
        container: null,
      },
      position: 1789,
      status: BallotStatus.AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
  ],
}

export const dummyBallotsNotAudited: { ballots: IBallot[] } = {
  ballots: [
    {
      id: 'ballot-id-1',
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id-1',
        tabulator: '11',
        container: null,
      },
      position: 313,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [
        {
          contestId: contest.id,
          interpretation: Interpretation.VOTE,
          choiceIds: [contest.choices[0].id],
          comment: 'Good ballot',
        },
      ],
      auditBoard: dummyBoards()[0],
    },
    {
      id: 'ballot-id-2',
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id-1',
        tabulator: '11',
        container: null,
      },
      position: 2112,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[0],
    },
    {
      id: 'ballot-id-3',
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id-1',
        tabulator: '11',
        container: null,
      },
      position: 1789,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[0],
    },
    {
      id: 'ballot-id-4',
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id-2',
        tabulator: '11',
        container: null,
      },
      position: 313,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[0],
    },
    {
      id: 'ballot-id-5',
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id-2',
        tabulator: '11',
        container: null,
      },
      position: 2112,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[0],
    },
    {
      id: 'ballot-id-6',
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id-2',
        tabulator: '11',
        container: null,
      },
      position: 1789,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[0],
    },
    {
      id: 'ballot-id-7',
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id-3',
        tabulator: '11',
        container: null,
      },
      position: 313,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[0],
    },
    {
      id: 'ballot-id-8',
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id-3',
        tabulator: '11',
        container: null,
      },
      position: 2112,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[0],
    },
    {
      id: 'ballot-id-9',
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id-3',
        tabulator: '11',
        container: null,
      },
      position: 1789,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[0],
    },
    {
      id: 'ballot-id-10',
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id-4',
        tabulator: '11',
        container: null,
      },
      position: 313,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[0],
    },
    {
      id: 'ballot-id-11',
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id-4',
        tabulator: '11',
        container: null,
      },
      position: 2112,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-12',
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id-4',
        tabulator: '11',
        container: null,
      },
      position: 1789,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-13',
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id-5',
        tabulator: '11',
        container: null,
      },
      position: 313,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-14',
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id-5',
        tabulator: '11',
        container: null,
      },
      position: 2112,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-15',
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id-5',
        tabulator: '11',
        container: null,
      },
      position: 1789,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-16',
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id-6',
        tabulator: '11',
        container: null,
      },
      position: 313,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-17',
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id-6',
        tabulator: '11',
        container: null,
      },
      position: 2112,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-18',
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id-6',
        tabulator: '11',
        container: null,
      },
      position: 1789,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-19',
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id-7',
        tabulator: '11',
        container: null,
      },
      position: 313,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-20',
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id-7',
        tabulator: '11',
        container: null,
      },
      position: 2112,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-21',
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id-7',
        tabulator: '11',
        container: null,
      },
      position: 1789,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-22',
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id-8',
        tabulator: '11',
        container: null,
      },
      position: 313,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-23',
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id-8',
        tabulator: '11',
        container: null,
      },
      position: 2112,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-24',
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id-8',
        tabulator: '11',
        container: null,
      },
      position: 1789,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-25',
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id-9',
        tabulator: '11',
        container: null,
      },
      position: 313,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-26',
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id-9',
        tabulator: '11',
        container: null,
      },
      position: 2112,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
    {
      id: 'ballot-id-27',
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id-9',
        tabulator: '11',
        container: null,
      },
      position: 1789,
      status: BallotStatus.NOT_AUDITED,
      interpretations: [],
      auditBoard: dummyBoards()[1],
    },
  ],
}

export default {
  dummyBoards,
  dummyBallots,
  dummyBallotsNotAudited,
}
