from r2b2.athena import Athena as Athena
from r2b2.cli import cli as cli
from r2b2.contest import Contest as Contest, ContestType as ContestType
from r2b2.minerva import Minerva as Minerva
from typing import Any

default_contest: Any

def test_simple_athena() -> None: ...
def test_athena_minerva_paper() -> None: ...
def test_athena_execute_round() -> None: ...
def test_interactive_athena() -> None: ...
def test_bulk_athena() -> None: ...
def test_athena_next_sample_size() -> None: ...
def test_exceptions() -> None: ...
