from click.testing import CliRunner as CliRunner
from r2b2.cli import cli as cli
from r2b2.contest import Contest as Contest, ContestType as ContestType
from r2b2.eor_bravo import EOR_BRAVO as EOR_BRAVO
from typing import Any

default_contest: Any
tol: float

def test_simple_eor_bravo() -> None: ...
def test_eor_bravo_kmins() -> None: ...
def test_min_sample_size() -> None: ...
def test_eor_bravo_first_round_estimate() -> None: ...
def test_eor_bravo_second_round_estimate() -> None: ...
def test_execute_round_eor_bravo() -> None: ...
