from r2b2.cli import cli as cli
from r2b2.contest import Contest as Contest, ContestType as ContestType
from r2b2.minerva import Minerva as Minerva
from typing import Any

default_contest: Any
tol: float

def test_simple_minerva() -> None: ...
def test_min_sample_size() -> None: ...
def test_kmin_upper_bound() -> None: ...
def test_minerva_first_round_estimate() -> None: ...
def test_minerva_first_round_gaussian_estimate() -> None: ...
def test_minerva_second_round_estimate() -> None: ...
def test_minerva_georgia_senate_2020() -> None: ...
def test_minerva_kmins() -> None: ...
def test_execute_round_minerva() -> None: ...
def test_interactive_minerva() -> None: ...
def test_next_sample_size_minerva() -> None: ...
def test_multiple_candidate_minerva() -> None: ...
def test_bulk_minerva() -> None: ...
def test_sentinel() -> None: ...
def test_exceptions() -> None: ...
