from r2b2.contest import Contest as Contest, ContestType as ContestType

def test_simple_contest() -> None: ...
def test_sorting_tally() -> None: ...
def test_pairwise_sub_contests() -> None: ...
def test_repr() -> None: ...
def test_str() -> None: ...
def test_initialization_errors() -> None: ...
