import { IAuditBoard } from '../../types'

export const dummyBoard: IAuditBoard[] = [
  {
    id: '123',
    name: 'Audit Board #1',
    members: [],
  },
  {
    id: '123',
    name: 'Audit Board #1',
    members: [
      {
        name: 'John Doe',
        affiliation: '',
      },
      {
        name: 'Jane Doe',
        affiliation: 'LIB',
      },
    ],
  },
  {
    id: '123',
    name: 'Audit Board #1',
    members: [
      {
        name: 'John Doe',
        affiliation: '',
      },
      {
        name: 'Jane Doe',
        affiliation: 'LIB',
      },
    ],
    ballots: [
      {
        tabulator: '11',
        batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        position: '313',
        status: 'NOT_AUDITED',
        vote: null,
        comment: '',
        id: '1',
      },
      {
        tabulator: '17',
        batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        position: '2112',
        status: 'NOT_AUDITED',
        vote: null,
        comment: '',
        id: '2',
      },
      {
        tabulator: '23',
        batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        position: '1789',
        status: 'NOT_AUDITED',
        vote: null,
        comment: '',
        id: '3',
      },
      {
        tabulator: '17',
        batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        position: '2112',
        status: 'NOT_AUDITED',
        vote: null,
        comment: '',
        id: '4',
      },
      {
        tabulator: '23',
        batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        position: '1789',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '5',
      },
    ],
  },
  {
    id: '123',
    name: 'Audit Board #1',
    members: [
      {
        name: 'John Doe',
        affiliation: '',
      },
      {
        name: 'Jane Doe',
        affiliation: 'LIB',
      },
    ],
    ballots: [
      {
        tabulator: '11',
        batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        position: '313',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '1',
      },
      {
        tabulator: '17',
        batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        position: '2112',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '2',
      },
      {
        tabulator: '23',
        batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        position: '1789',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '3',
      },
      {
        tabulator: '17',
        batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        position: '2112',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '4',
      },
      {
        tabulator: '23',
        batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        position: '1789',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '5',
      },
      {
        tabulator: '11',
        batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        position: '313',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '6',
      },
      {
        tabulator: '17',
        batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        position: '2112',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '7',
      },
      {
        tabulator: '23',
        batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        position: '1789',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '8',
      },
      {
        tabulator: '17',
        batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        position: '2112',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '9',
      },
      {
        tabulator: '23',
        batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        position: '1789',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '10',
      },
      {
        tabulator: '11',
        batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        position: '313',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '11',
      },
      {
        tabulator: '17',
        batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        position: '2112',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '12',
      },
      {
        tabulator: '23',
        batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        position: '1789',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '13',
      },
      {
        tabulator: '17',
        batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        position: '2112',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '14',
      },
      {
        tabulator: '23',
        batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        position: '1789',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '15',
      },
      {
        tabulator: '11',
        batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        position: '313',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '16',
      },
      {
        tabulator: '17',
        batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        position: '2112',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '17',
      },
      {
        tabulator: '23',
        batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        position: '1789',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '18',
      },
      {
        tabulator: '17',
        batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        position: '2112',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '19',
      },
      {
        tabulator: '23',
        batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        position: '1789',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '20',
      },
      {
        tabulator: '11',
        batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        position: '313',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '21',
      },
      {
        tabulator: '17',
        batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        position: '2112',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '22',
      },
      {
        tabulator: '23',
        batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        position: '1789',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '23',
      },
      {
        tabulator: '17',
        batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        position: '2112',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '24',
      },
      {
        tabulator: '23',
        batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        position: '1789',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '25',
      },
      {
        tabulator: '11',
        batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        position: '313',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '26',
      },
      {
        tabulator: '17',
        batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        position: '2112',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '27',
      },
      {
        tabulator: '23',
        batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        position: '1789',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '28',
      },
      {
        tabulator: '17',
        batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        position: '2112',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '29',
      },
      {
        tabulator: '23',
        batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        position: '1789',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '30',
      },
      {
        tabulator: '11',
        batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        position: '313',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '31',
      },
      {
        tabulator: '17',
        batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        position: '2112',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '32',
      },
      {
        tabulator: '23',
        batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        position: '1789',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '33',
      },
      {
        tabulator: '17',
        batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        position: '2112',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '34',
      },
      {
        tabulator: '23',
        batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        position: '1789',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '35',
      },
      {
        tabulator: '11',
        batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        position: '313',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '36',
      },
      {
        tabulator: '17',
        batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        position: '2112',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '37',
      },
      {
        tabulator: '23',
        batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        position: '1789',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '38',
      },
      {
        tabulator: '17',
        batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        position: '2112',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '39',
      },
      {
        tabulator: '23',
        batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        position: '1789',
        status: 'AUDITED',
        vote: null,
        comment: '',
        id: '40',
      },
    ],
  },
]

export default {
  dummyBoard,
}
