import { IAuditBoard, IBallot } from '../../types'

export const dummyBallots: { ballots: IBallot[] } = {
  ballots: [
    {
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 313,
      status: 'AUDITED',
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 2112,
      status: null,
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 1789,
      status: 'AUDITED',
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 2112,
      status: null,
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 1789,
      status: 'AUDITED',
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 313,
      status: 'AUDITED',
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 2112,
      status: null,
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 1789,
      status: 'AUDITED',
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 2112,
      status: null,
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 1789,
      status: 'AUDITED',
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 313,
      status: 'AUDITED',
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 2112,
      status: null,
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 1789,
      status: 'AUDITED',
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 2112,
      status: null,
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 1789,
      status: 'AUDITED',
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 313,
      status: 'AUDITED',
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 2112,
      status: null,
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 1789,
      status: 'AUDITED',
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 2112,
      status: null,
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 1789,
      status: 'AUDITED',
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 313,
      status: 'AUDITED',
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 2112,
      status: null,
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 1789,
      status: 'AUDITED',
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 2112,
      status: null,
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 1789,
      status: 'AUDITED',
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 313,
      status: 'AUDITED',
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 2112,
      status: null,
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 1789,
      status: 'AUDITED',
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 2112,
      status: null,
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 1789,
      status: 'AUDITED',
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 313,
      status: 'AUDITED',
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 2112,
      status: null,
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 1789,
      status: 'AUDITED',
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 2112,
      status: null,
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 1789,
      status: 'AUDITED',
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 13 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 313,
      status: 'AUDITED',
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 2112,
      status: null,
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 1789,
      status: 'AUDITED',
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 19 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 2112,
      status: null,
      vote: null,
      comment: '',
      timesSampled: 1,
    },
    {
      batch: {
        name: '0003-04-Precinct 29 (Jonesboro Fire Department)',
        id: 'batch-id',
        tabulator: '11',
      },
      position: 1789,
      status: 'AUDITED',
      vote: null,
      comment: '',
      timesSampled: 1,
    },
  ],
}

export const dummyBoard: IAuditBoard[] = [
  {
    id: '123',
    name: 'Audit Board #1',
    members: [],
  },
  {
    id: '123',
    name: 'Audit Board #1',
    members: [
      {
        name: 'John Doe',
        affiliation: '',
      },
      {
        name: 'Jane Doe',
        affiliation: 'LIB',
      },
    ],
  },
]

export default {
  dummyBoard,
  dummyBallots,
}
