"""Constraint naming convention

Revision ID: 690f668a930a
Revises: 
Create Date: 2020-07-06 17:58:31.820157+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690f668a930a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_audit_board_jurisdiction_id_round_id_name'), 'audit_board', ['jurisdiction_id', 'round_id', 'name'])
    op.create_unique_constraint(op.f('uq_audit_board_passphrase'), 'audit_board', ['passphrase'])
    op.drop_constraint('audit_board_jurisdiction_id_round_id_name_key', 'audit_board', type_='unique')
    op.drop_constraint('audit_board_passphrase_key', 'audit_board', type_='unique')
    op.create_unique_constraint(op.f('uq_batch_jurisdiction_id_name'), 'batch', ['jurisdiction_id', 'name'])
    op.drop_constraint('batch_jurisdiction_id_name_key', 'batch', type_='unique')
    op.create_unique_constraint(op.f('uq_contest_choice_id_contest_id'), 'contest_choice', ['id', 'contest_id'])
    op.drop_constraint('contest_choice_id_contest_id_key', 'contest_choice', type_='unique')
    op.create_unique_constraint(op.f('uq_election_organization_id_audit_name'), 'election', ['organization_id', 'audit_name'])
    op.drop_constraint('election_organization_id_audit_name_key', 'election', type_='unique')
    op.create_unique_constraint(op.f('uq_jurisdiction_election_id_name'), 'jurisdiction', ['election_id', 'name'])
    op.drop_constraint('jurisdiction_election_id_name_key', 'jurisdiction', type_='unique')
    op.create_unique_constraint(op.f('uq_round_election_id_round_num'), 'round', ['election_id', 'round_num'])
    op.drop_constraint('round_election_id_round_num_key', 'round', type_='unique')
    op.create_unique_constraint(op.f('uq_sampled_ballot_batch_id_ballot_position'), 'sampled_ballot', ['batch_id', 'ballot_position'])
    op.drop_constraint('sampled_ballot_batch_id_ballot_position_key', 'sampled_ballot', type_='unique')
    op.create_unique_constraint(op.f('uq_user_email'), 'user', ['email'])
    op.create_unique_constraint(op.f('uq_user_external_id'), 'user', ['external_id'])
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_constraint('user_external_id_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_external_id_key', 'user', ['external_id'])
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.drop_constraint(op.f('uq_user_external_id'), 'user', type_='unique')
    op.drop_constraint(op.f('uq_user_email'), 'user', type_='unique')
    op.create_unique_constraint('sampled_ballot_batch_id_ballot_position_key', 'sampled_ballot', ['batch_id', 'ballot_position'])
    op.drop_constraint(op.f('uq_sampled_ballot_batch_id_ballot_position'), 'sampled_ballot', type_='unique')
    op.create_unique_constraint('round_election_id_round_num_key', 'round', ['election_id', 'round_num'])
    op.drop_constraint(op.f('uq_round_election_id_round_num'), 'round', type_='unique')
    op.create_unique_constraint('jurisdiction_election_id_name_key', 'jurisdiction', ['election_id', 'name'])
    op.drop_constraint(op.f('uq_jurisdiction_election_id_name'), 'jurisdiction', type_='unique')
    op.create_unique_constraint('election_organization_id_audit_name_key', 'election', ['organization_id', 'audit_name'])
    op.drop_constraint(op.f('uq_election_organization_id_audit_name'), 'election', type_='unique')
    op.create_unique_constraint('contest_choice_id_contest_id_key', 'contest_choice', ['id', 'contest_id'])
    op.drop_constraint(op.f('uq_contest_choice_id_contest_id'), 'contest_choice', type_='unique')
    op.create_unique_constraint('batch_jurisdiction_id_name_key', 'batch', ['jurisdiction_id', 'name'])
    op.drop_constraint(op.f('uq_batch_jurisdiction_id_name'), 'batch', type_='unique')
    op.create_unique_constraint('audit_board_passphrase_key', 'audit_board', ['passphrase'])
    op.create_unique_constraint('audit_board_jurisdiction_id_round_id_name_key', 'audit_board', ['jurisdiction_id', 'round_id', 'name'])
    op.drop_constraint(op.f('uq_audit_board_passphrase'), 'audit_board', type_='unique')
    op.drop_constraint(op.f('uq_audit_board_jurisdiction_id_round_id_name'), 'audit_board', type_='unique')
    # ### end Alembic commands ###
