import { Audit } from '../../types'

export const statusStates: Audit[] = [
  {
    name: '',
    riskLimit: '',
    randomSeed: '',
    contests: [],
    jurisdictions: [],
    rounds: [],
  },
  {
    contests: [
      {
        choices: [
          {
            id: 'choice-1',
            name: 'choice one',
            numVotes: 792,
          },
          {
            id: 'choice-2',
            name: 'choice two',
            numVotes: 1325,
          },
        ],
        id: 'contest-1',
        name: 'contest name',
        winners: '1',
        totalBallotsCast: '2123',
      },
    ],
    jurisdictions: [],
    rounds: [
      {
        contests: [
          {
            endMeasurements: {
              isComplete: null,
              pvalue: null,
            },
            id: 'contest-1',
            results: {},
            sampleSize: null,
            sampleSizeOptions: null,
          },
        ],
        endedAt: null,
        startedAt: 'Thu, 18 Jul 2019 16:34:07 GMT',
      },
    ],
    name: 'contest name',
    randomSeed: '123456789',
    riskLimit: '1',
  },
  {
    contests: [
      {
        choices: [
          {
            id: 'choice-1',
            name: 'choice one',
            numVotes: 792,
          },
          {
            id: 'choice-2',
            name: 'choice two',
            numVotes: 1325,
          },
        ],
        id: 'contest-1',
        name: 'contest name',
        winners: '1',
        totalBallotsCast: '2123',
      },
    ],
    jurisdictions: [],
    rounds: [
      {
        contests: [
          {
            endMeasurements: {
              isComplete: null,
              pvalue: null,
            },
            id: 'contest-1',
            results: {},
            sampleSize: null,
            sampleSizeOptions: [
              { size: 269, type: 'ASN', prob: null },
              { size: 379, prob: 0.8, type: null },
              { size: 78, prob: null, type: null },
            ],
          },
        ],
        endedAt: null,
        startedAt: 'Thu, 18 Jul 2019 16:34:07 GMT',
      },
    ],
    name: 'contest name',
    randomSeed: '123456789',
    riskLimit: '1',
  },
  {
    contests: [
      {
        choices: [
          {
            id: 'choice-1',
            name: 'choice one',
            numVotes: 792,
          },
          {
            id: 'choice-2',
            name: 'choice two',
            numVotes: 1325,
          },
        ],
        id: 'contest-1',
        name: 'contest name',
        totalBallotsCast: '2123',
        winners: '1',
      },
    ],
    jurisdictions: [
      {
        auditBoards: [
          {
            id: 'audit-board-1',
            name: 'Audit Board #1',
            members: [],
          },
        ],
        ballotManifest: {
          filename: null,
          numBallots: null,
          numBatches: null,
          uploadedAt: null,
        },
        contests: ['contest-1'],
        id: 'jurisdiction-1',
        name: 'Jurisdiction 1',
      },
    ],
    rounds: [
      {
        contests: [
          {
            endMeasurements: {
              isComplete: null,
              pvalue: null,
            },
            id: 'contest-1',
            results: {},
            sampleSize: null,
            sampleSizeOptions: [
              { size: 269, type: 'ASN', prob: null },
              { size: 379, prob: 0.8, type: null },
              { size: 78, prob: null, type: null },
            ],
          },
        ],
        endedAt: null,
        startedAt: 'Thu, 18 Jul 2019 16:34:07 GMT',
      },
    ],
    name: 'contest name',
    randomSeed: '123456789',
    riskLimit: '1',
  },
  {
    contests: [
      {
        choices: [
          {
            id: 'choice-1',
            name: 'choice one',
            numVotes: 792,
          },
          {
            id: 'choice-2',
            name: 'choice two',
            numVotes: 1325,
          },
        ],
        id: 'contest-1',
        name: 'contest name',
        winners: '1',
        totalBallotsCast: '2123',
      },
    ],
    jurisdictions: [
      {
        auditBoards: [
          {
            id: 'audit-board-1',
            name: 'Audit Board #1',
            members: [],
            ballots: [
              {
                tabulator: '11',
                batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
                position: '313',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '1',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '2',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '3',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '4',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '5',
              },
              {
                tabulator: '11',
                batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
                position: '313',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '6',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '7',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '8',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '9',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '10',
              },
              {
                tabulator: '11',
                batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
                position: '313',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '11',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '12',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '13',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '14',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '15',
              },
              {
                tabulator: '11',
                batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
                position: '313',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '16',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '17',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '18',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '19',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '20',
              },
              {
                tabulator: '11',
                batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
                position: '313',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '21',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '22',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '23',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '24',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '25',
              },
              {
                tabulator: '11',
                batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
                position: '313',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '26',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '27',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '28',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '29',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '30',
              },
              {
                tabulator: '11',
                batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
                position: '313',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '31',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '32',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '33',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '34',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '35',
              },
              {
                tabulator: '11',
                batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
                position: '313',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '36',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '37',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '38',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '39',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '40',
              },
            ],
          },
        ],
        ballotManifest: {
          filename: 'Ballot Manifest May 2019 Election - WYNADOTTE.csv',
          numBallots: 2117,
          numBatches: 10,
          uploadedAt: 'Thu, 18 Jul 2019 16:34:07 GMT',
        },
        contests: ['contest-1'],
        id: 'jurisdiction-1',
        name: 'Jurisdiction 1',
      },
    ],
    rounds: [
      {
        contests: [
          {
            endMeasurements: {
              isComplete: null,
              pvalue: null,
            },
            id: 'contest-1',
            results: {},
            sampleSize: 379,
            sampleSizeOptions: [
              { size: 269, type: 'ASN', prob: null },
              { size: 379, prob: 0.8, type: null },
              { size: 78, prob: null, type: null },
            ],
          },
        ],
        endedAt: null,
        startedAt: 'Thu, 18 Jul 2019 16:34:07 GMT',
      },
    ],
    name: 'contest name',
    randomSeed: '123456789',
    riskLimit: '1',
  },
  {
    contests: [
      {
        choices: [
          {
            id: 'choice-1',
            name: 'choice one',
            numVotes: 792,
          },
          {
            id: 'choice-2',
            name: 'choice two',
            numVotes: 1325,
          },
        ],
        id: 'contest-1',
        name: 'contest name',
        winners: '1',
        totalBallotsCast: '2123',
      },
    ],
    jurisdictions: [
      {
        auditBoards: [
          {
            id: 'audit-board-1',
            name: 'Audit Board #1',
            members: [],
            ballots: [
              {
                tabulator: '11',
                batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
                position: '313',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '1',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '2',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '3',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '4',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '5',
              },
              {
                tabulator: '11',
                batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
                position: '313',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '6',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '7',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '8',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '9',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '10',
              },
              {
                tabulator: '11',
                batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
                position: '313',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '11',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '12',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '13',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '14',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '15',
              },
              {
                tabulator: '11',
                batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
                position: '313',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '16',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '17',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '18',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '19',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '20',
              },
              {
                tabulator: '11',
                batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
                position: '313',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '21',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '22',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '23',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '24',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '25',
              },
              {
                tabulator: '11',
                batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
                position: '313',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '26',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '27',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '28',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '29',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '30',
              },
              {
                tabulator: '11',
                batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
                position: '313',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '31',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '32',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '33',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '34',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '35',
              },
              {
                tabulator: '11',
                batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
                position: '313',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '36',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '37',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '38',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '39',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '40',
              },
            ],
          },
        ],
        ballotManifest: {
          filename: 'Ballot Manifest May 2019 Election - WYNADOTTE.csv',
          numBallots: 2117,
          numBatches: 10,
          uploadedAt: 'Thu, 18 Jul 2019 16:34:07 GMT',
        },
        contests: ['contest-1'],
        id: 'jurisdiction-1',
        name: 'Jurisdiction 1',
      },
    ],
    rounds: [
      {
        contests: [
          {
            endMeasurements: {
              isComplete: true,
              pvalue: 0.00020431431380638307,
            },
            id: 'contest-1',
            results: {
              'choice-1': 100,
              'choice-2': 167,
            },
            sampleSize: 379,
            sampleSizeOptions: [
              { size: 269, type: 'ASN', prob: null },
              { size: 379, prob: 0.8, type: null },
              { size: 78, prob: null, type: null },
            ],
          },
        ],
        endedAt: 'Thu, 18 Jul 2019 16:59:34 GMT',
        startedAt: 'Thu, 18 Jul 2019 16:34:07 GMT',
      },
    ],
    name: 'contest name',
    randomSeed: '123456789',
    riskLimit: '1',
  },
  {
    contests: [
      {
        choices: [
          {
            id: 'choice-1',
            name: 'choice one',
            numVotes: 792,
          },
          {
            id: 'choice-2',
            name: 'choice two',
            numVotes: 1325,
          },
        ],
        id: 'contest-1',
        name: 'contest name',
        totalBallotsCast: '2123',
        winners: '1',
      },
    ],
    jurisdictions: [
      {
        auditBoards: [
          {
            id: 'audit-board-1',
            name: 'Audit Board #1',
            members: [],
            ballots: [
              {
                tabulator: '11',
                batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
                position: '313',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '1',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '2',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '3',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '4',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '5',
              },
              {
                tabulator: '11',
                batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
                position: '313',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '6',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '7',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '8',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '9',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '10',
              },
              {
                tabulator: '11',
                batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
                position: '313',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '11',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '12',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '13',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '14',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '15',
              },
              {
                tabulator: '11',
                batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
                position: '313',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '16',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '17',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '18',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '19',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '20',
              },
              {
                tabulator: '11',
                batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
                position: '313',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '21',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '22',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '23',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '24',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '25',
              },
              {
                tabulator: '11',
                batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
                position: '313',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '26',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '27',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '28',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '29',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '30',
              },
              {
                tabulator: '11',
                batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
                position: '313',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '31',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '32',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '33',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '34',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '35',
              },
              {
                tabulator: '11',
                batch: '0003-04-Precinct 13 (Jonesboro Fire Department)',
                position: '313',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '36',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '37',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '38',
              },
              {
                tabulator: '17',
                batch: '0003-04-Precinct 19 (Jonesboro Fire Department)',
                position: '2112',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '39',
              },
              {
                tabulator: '23',
                batch: '0003-04-Precinct 29 (Jonesboro Fire Department)',
                position: '1789',
                status: 'AUDITED',
                vote: null,
                comment: '',
                id: '40',
              },
            ],
          },
        ],
        ballotManifest: {
          filename: 'Ballot Manifest May 2019 Election - WYNADOTTE.csv',
          numBallots: 2117,
          numBatches: 10,
          uploadedAt: 'Thu, 18 Jul 2019 16:34:07 GMT',
        },
        contests: ['contest-1'],
        id: 'jurisdiction-1',
        name: 'Jurisdiction 1',
      },
    ],
    rounds: [
      {
        contests: [
          {
            endMeasurements: {
              isComplete: null,
              pvalue: null,
            },
            id: 'contest-1',
            results: {},
            sampleSize: null,
            sampleSizeOptions: null,
          },
        ],
        endedAt: null,
        startedAt: 'Thu, 18 Jul 2019 16:34:07 GMT',
      },
    ],
    name: 'contest name',
    randomSeed: '123456789',
    riskLimit: '1',
  },
]

export const ballotManifest = new File(
  ['ballot manifest'],
  'ballotManifest.csv',
  { type: 'text/csv' }
)

export default statusStates
