# pylint: disable=invalid-name
"""Adding ballotPollingType

Revision ID: 0cec6411a0f2
Revises: b5fcf654c681
Create Date: 2020-10-30 19:50:36.944418+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0cec6411a0f2"
down_revision = "b5fcf654c681"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ballot_polling_type_enum = sa.dialects.postgresql.ENUM(
        "BRAVO", "MINERVA", name="ballotpollingtype"
    )
    ballot_polling_type_enum.create(op.get_bind())
    op.add_column(
        "election", sa.Column("ballot_polling_type", ballot_polling_type_enum),
    )
    op.execute(
        """
        UPDATE election
        SET ballot_polling_type = 'BRAVO'
        """
    )
    op.alter_column("election", "ballot_polling_type", nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
