# pylint: disable=invalid-name
"""creating audit math type column

Revision ID: 1f09f891a83d
Revises: 0cec6411a0f2
Create Date: 2020-11-03 16:55:10.372158+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1f09f891a83d"
down_revision = "0cec6411a0f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    audit_math_type_enum = sa.dialects.postgresql.ENUM(
        "BRAVO", "MINERVA", "SuperSimple", "MACRO", name="auditmathtype"
    )
    audit_math_type_enum.create(op.get_bind())
    op.add_column(
        "election", sa.Column("audit_math_type", audit_math_type_enum),
    )
    op.execute(
        """
        UPDATE election
        SET audit_math_type = 'BRAVO'
        """
    )
    op.alter_column("election", "audit_math_type", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
