# pylint: disable=invalid-name
"""Election.is_deleted

Revision ID: 2bab20f6482a
Revises: 07859b6b370b
Create Date: 2021-03-25 23:00:46.683986+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2bab20f6482a"
down_revision = "07859b6b370b"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column("election", sa.Column("is_deleted", sa.Boolean()))


def downgrade():  # pragma: no cover
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column("election", "is_deleted")
    # ### end Alembic commands ###
