"""Batch.has_cvrs

Revision ID: 342f43b1c9d9
Revises: 5bb25bdd56b7
Create Date: 2021-02-18 20:19:45.419887+00:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "342f43b1c9d9"
down_revision = "5bb25bdd56b7"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column("batch", sa.Column("has_cvrs", sa.Boolean(), nullable=True))


def downgrade():  # pragma: no cover
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column("batch", "has_cvrs")
    # ### end Alembic commands ###
