# pylint: disable=invalid-name
"""AuditType.BATCH_COMPARISON

Revision ID: 3edc260ab0b1
Revises: aa3978570981
Create Date: 2020-09-28 22:11:46.110113+00:00

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "3edc260ab0b1"
down_revision = "aa3978570981"
branch_labels = None
depends_on = None


def upgrade():
    # Alembic doesn't support changing enums, so we have to do with with raw
    # SQL. You can't alter an enum inside a transaction block (which this
    # function is wrapped in by Alembic), so first we have to commit the
    # transaction.
    # https://github.com/sqlalchemy/alembic/issues/123#issuecomment-441882887
    op.execute("COMMIT")
    op.execute("ALTER TYPE audittype ADD VALUE 'BALLOT_COMPARISON'")


def downgrade():  # pragma: no cover
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
