# pylint: disable=invalid-name
"""Remove OfflineBatchResultChangelog

Revision ID: 3efe804f6952
Revises: 5238d088cf62
Create Date: 2020-12-07 23:08:47.025411+00:00

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "3efe804f6952"
down_revision = "5238d088cf62"
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table("offline_batch_result_changelog")


def downgrade():  # pragma: no cover
    pass
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('offline_batch_result_changelog',
    # sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    # sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    # sa.Column('user_id', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    # sa.Column('jurisdiction_id', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    # sa.Column('before', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    # sa.Column('after', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdiction.id'], name='offline_batch_result_changelog_jurisdiction_id_fkey', ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='offline_batch_result_changelog_user_id_fkey', ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('jurisdiction_id', 'user_id', 'created_at', name='offline_batch_result_changelog_pkey')
    # )
    # # ### end Alembic commands ###
