# pylint: disable=invalid-name
"""BackgroundTask

Revision ID: 8b6b89bfbc97
Revises: c2b90f147183
Create Date: 2021-01-26 18:51:57.731262+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8b6b89bfbc97"
down_revision = "c2b90f147183"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "background_task",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=200), nullable=False),
        sa.Column("task_name", sa.Enum("DRAW_SAMPLE", name="taskname"), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("background_task_pkey")),
    )
    op.add_column(
        "round", sa.Column("draw_sample_task_id", sa.String(length=200), nullable=True)
    )
    op.create_foreign_key(
        op.f("round_draw_sample_task_id_fkey"),
        "round",
        "background_task",
        ["draw_sample_task_id"],
        ["id"],
        ondelete="cascade",
    )


def downgrade():  # pragma: no cover
    pass
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(
    #     op.f("round_draw_sample_task_id_fkey"), "round", type_="foreignkey"
    # )
    # op.drop_column("round", "draw_sample_task_id")
    # op.drop_table("background_task")
    # # ### end Alembic commands ###
