# pylint: disable=invalid-name
"""Jurisdiction.contest_name_standardizations

Revision ID: 9d9c4e058cb2
Revises: f8e901e92f0a
Create Date: 2021-04-15 21:55:13.793690+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9d9c4e058cb2"
down_revision = "f8e901e92f0a"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        "jurisdiction",
        sa.Column("contest_name_standardizations", sa.JSON(), nullable=True),
    )


def downgrade():  # pragma: no cover
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('jurisdiction', 'contest_name_standardizations')
    # ### end Alembic commands ###
