"""Remove File.contents

Revision ID: bc97ac0e8267
Revises: df3c0681fad9
Create Date: 2021-12-13 23:53:01.691311+00:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bc97ac0e8267"
down_revision = "df3c0681fad9"
branch_labels = None
depends_on = None


def upgrade():
    op.alter_column(
        "file", "storage_path", existing_type=sa.VARCHAR(length=250), nullable=False
    )
    op.drop_column("file", "contents")


def downgrade():  # pragma: no cover
    pass
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column(
    #     "file", sa.Column("contents", sa.TEXT(), autoincrement=False, nullable=False)
    # )
    # op.alter_column(
    #     "file", "storage_path", existing_type=sa.VARCHAR(length=250), nullable=True
    # )
    # # ### end Alembic commands ###
