"""Organization.name unique

Revision ID: c2b90f147183
Revises: 4aa612e28c2e
Create Date: 2021-01-07 23:41:25.373340+00:00

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "c2b90f147183"
down_revision = "4aa612e28c2e"
branch_labels = None
depends_on = None


def upgrade():
    op.create_unique_constraint(op.f("organization_name_key"), "organization", ["name"])


def downgrade():  # pragma: no cover
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f('organization_name_key'), 'organization', type_='unique')
    # ### end Alembic commands ###
